version: 2


project_name: pmsg


before:
  hooks:
    - go mod tidy


builds:
  - binary: pmsg

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/pmsg/version.AppName={{.ProjectName}}
      - -X github.com/lenye/pmsg/version.Version={{.Version}}
      - -X github.com/lenye/pmsg/version.BuildCommit={{.ShortCommit}}
      - -X github.com/lenye/pmsg/version.BuildTime={{.CommitDate}}
      - -extldflags
      - -static
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - "amd64"
      - "arm64"
      - "riscv64"
      - "s390x"
      - "ppc64le"
      - "386"
      - "arm"
    goarm:
      - 7
      - 6
    ignore:
      - goos: windows
        goarch: "arm"
    mod_timestamp: '{{ .CommitTimestamp }}'


archives:
  - id: pmsg
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    formats: [ "tar.gz" ]
    format_overrides:
      - goos: windows
        formats: [ "zip" ]


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums_sha256.txt"
  algorithm: sha256


changelog:
  filters:
    exclude:
      - '^wip:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^chore:'
      - '^ci:'


release:
  draft: true
  replace_existing_draft: true


dockers:
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-x86_64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-ppc64le"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-ppc64le"
    use: buildx
    goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile.ppc64le
    build_flag_templates:
      - "--pull"
      - "--platform=linux/ppc64le"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-s390x"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-s390x"
    use: buildx
    goos: linux
    goarch: s390x
    dockerfile: Dockerfile.s390x
    build_flag_templates:
      - "--pull"
      - "--platform=linux/s390x"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"


docker_manifests:
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-ppc64le
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-s390x
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-ppc64le
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-s390x
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-x86_64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-ppc64le
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-s390x
